spring:
  profiles:
    active: local
  datasource:
    url: ${AVA_LAB_H2_MEM_URL:jdbc:h2:mem:testdb}
    username: ${AVA_LAB_H2_MEM_USER:sa}
    password: ${AVA_LAB_H2_MEM_PASSWORD:password}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        default_schema: ava_lab
  flyway:
    clean-disabled: false
    enabled: true
    schemas: ava_lab
  redis:
    host: ${REDIS_SERVER_HOST:localhost}
    port: ${REDIS_SERVER_PORT:6370}